### ISSUE TITLE
PCNN+ONE

### ISSUE THREAD

**Issue by charlesfufu** [ShomyLiu/pytorch-relation-extraction#10]
请问PCNN+One和传统的PCNN什么区别哈？

**Comment by ShomyLiu** [comment]
传统的PCNN 是全监督学习的关系抽取，对应Zeng 2014(Relation Classification via Convolutional Deep Neural Network)那篇文章.  PCNN+ONE对应Zeng 2015(Distant Supervision for Relation Extraction via Piecewise Convolutional Neural Networks) 这篇文章，研究远程监督的关系抽取。 在PCNN基础上，引用multiinstance Learning 就是在一个bag内选择一个instance，所以叫PCNN+ONE.

**Comment by charlesfufu** [comment]
> 传统的PCNN 是全监督学习的关系抽取，对应Zeng 2014(Relation Classification via Convolutional Deep Neural Network)那篇文章. PCNN+ONE对应Zeng 2015(Distant Supervision for Relation Extraction via Piecewise Convolutional Neural Networks) 这篇文章，研究远程监督的关系抽取。 在PCNN基础上，引用multiinstance Learning 就是在一个bag内选择一个instance，所以叫PCNN+ONE.



> 传统的PCNN 是全监督学习的关系抽取，对应Zeng 2014(Relation Classification via Convolutional Deep Neural Network)那篇文章. PCNN+ONE对应Zeng 2015(Distant Supervision for Relation Extraction via Piecewise Convolutional Neural Networks) 这篇文章，研究远程监督的关系抽取。 在PCNN基础上，引用multiinstance Learning 就是在一个bag内选择一个instance，所以叫PCNN+ONE.

学习了！！谢谢你的详细解答！

**Comment by charlesfufu** [comment]
> 传统的PCNN 是全监督学习的关系抽取，对应Zeng 2014(Relation Classification via Convolutional Deep Neural Network)那篇文章. PCNN+ONE对应Zeng 2015(Distant Supervision for Relation Extraction via Piecewise Convolutional Neural Networks) 这篇文章，研究远程监督的关系抽取。 在PCNN基础上，引用multiinstance Learning 就是在一个bag内选择一个instance，所以叫PCNN+ONE.

![image](https://user-images.githubusercontent.com/33311822/48310242-b2273780-e5c6-11e8-9238-041eb857d156.png)
![image](https://user-images.githubusercontent.com/33311822/48310289-d899a280-e5c7-11e8-8f1a-0697eb0707c0.png)

不好意思，原作者说在测试集每个bag选取一个，不知道这样做的意义是什么？感觉和你论文解释的不能相通啊

**Comment by ShomyLiu** [comment]
这个不是通用实验，是为了证明ATT的作用设计的。 att主要是解决一个bag内有多个instance的情况，所以为了进一步说明att的作用，设计了这一组实验。  而我博客里面的仅仅针对通用实验，计算PR曲线。
