### ISSUE TITLE
关于训练环境的问题

### ISSUE THREAD

**Issue by liuhuanyong** [ShomyLiu/pytorch-relation-extraction#15]
您好,这个一定需要cuda训练吗?如果想用cpu运行的话,需要怎么调整?

**Comment by ShomyLiu** [comment]
你好，代码中大部分地方都做了CPU环境的判断，您可以直接 --use_gpu=False 来关闭GPU。 因为后期调整的原因，可能有写代码忘记改为CPU模式，可以直接在对应位置修改即可。 去掉.cuda()

**Comment by liuhuanyong** [comment]
看到了,多谢!
