### ISSUE TITLE
reading-friendly data (ask for rel2id.json)?

### ISSUE THREAD

**Issue by WindChimeRan** [ShomyLiu/pytorch-relation-extraction#18]
The processed data are all numbers. I want to read the results and use magic in it.
Are there any **nyt_word_vec.json** and **rel2id.json** files for FilterNYT? In addition, I found these two jsons in OpenNRE. Do they match your NYT data?

Thanks.

**Comment by ShomyLiu** [comment]
Hi, both the FilterNYT and NYT datasets are released by the papers (i.e., Zeng 2015, Lin2016).
There are indeed no two jsons in FilterNYT used in Zeng 2015. There are only a vector.txt which can used to be map word id into word. 
As for NYT data in my repo is the same with OpenNRE.

**Comment by WindChimeRan** [comment]
That's very helpful, thanks
