### ISSUE TITLE
关于句子长度的问题

### ISSUE THREAD

**Issue by shuxiaobo** [ShomyLiu/pytorch-relation-extraction#2]
您好，请教一下，关于代码中，句子 max_len 设置的大小问题，想请问下，这个长度是原本数据集的设置吗？

**Comment by ShomyLiu** [comment]
@shuxiaobo  是的, PCNN_ONE 设置的大小即为80.，基本是覆盖了句子最长句子了 。 额外的2是又加了padding

**Comment by shuxiaobo** [comment]
OK，谢谢！

**Comment by 599177227** [comment]
请问加的2个padding 主要是干什么用的呢，句子的开头符和结尾符吗？@shuxiaobo
