### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by shiningliang** [ShomyLiu/pytorch-relation-extraction#26]
在filternyt.py的get_pos_feature中，您在计算pf1 pf2都多加2，padding时也是，请问是什么原理或者技巧吗？

**Comment by ShomyLiu** [comment]
你好， 这个padding主要是为了卷积之后的分段pooling 考虑。 如果不加padding，分段pooling不容易处理。

**Comment by shiningliang** [comment]
您看我理解的对不对，就是要把所有的句子padding到长度为80，额外的+2是为了区分句子的三段？

**Comment by ShomyLiu** [comment]
首尾的padding就是为了防止比如 第一个单词或者最后一个单词是entity的情况，这样第一段或者第三段就会为空，这样一些运算会出错。 所以要加padding

**Comment by shiningliang** [comment]
好的，非常感谢！！！
另外filternyt.py中map函数外面要套一个list，适配python3，哈哈

**Comment by ShomyLiu** [comment]
谢谢！修改了， 后续的更新都是基于Large数据集的，所以filter的就遗漏了，已更正。
