### ISSUE TITLE
关于predict函数

### ISSUE THREAD

**Issue by ShellingFord221** [ShomyLiu/pytorch-relation-extraction#28]
你好，predict函数里在计算每个sample的最大概率的时候，
                        if max_ins_prob[i] > tmp_prob:
                            pred_label = max_ins_label[i]
                            tmp_prob = max_ins_prob[i]
                    else:
                        if max_ins_prob[i] > tmp_NA_prob:
                            tmp_NA_prob = max_ins_prob[i]
为什么要与temp的概率比较，并且在循环中只将最大的概率保留下来？是因为只考虑这个bag中概率最大的sample吗？别的sample的结果就不考虑在P,R值中了？谢谢！

**Comment by ShomyLiu** [comment]
对，只考虑bag内可能性最大的那个句子，因为考虑的是bag-level
