### ISSUE TITLE
关于recall的计算

### ISSUE THREAD

**Issue by ShellingFord221** [ShomyLiu/pytorch-relation-extraction#29]
在eval_metric()函数中，你的recall值是这样计算的：
recall = tp * 1.0 / positive_num，其中positive_num是实际标签非NA的bag个数。
但是recall的定义是 recall = tp / (tp + fn)，fn指的是预测为NA、实际为非NA，而tp指的是预测为非NA，实际为非NA，但标签预测正确的，也就是说，tp + fn 的值会比positive_num小一些，这样用你的方式计算出的recall值会比按照定义的方式计算出的值小一些。
想问下这个地方是怎么回事呢？谢谢！

**Comment by ShomyLiu** [comment]
一般情况，recall就是召回，看看能覆盖多少正样例(非NA). 所以直接/positive num 也是没问题。
严格来说，你说的计算方法是对的，你可以测试下，这俩值的差距我记得不大。

最近比较忙，回复不太及时，见谅，后续会一一回复issue。

**Comment by ShellingFord221** [comment]
好的~谢谢~~

**Comment by ShellingFord221** [comment]
你好，想问下假如一个sample的标签是5，但是我预测的是3（假定0是NA类），那么这个sample是FP还是FN呢？谢谢！

**Comment by ShellingFord221** [comment]
另外，在你的代码中，FP指的是样本标签为NA，且预测为非NA的，FN指的是样本标签为非NA，且预测为NA的，但是根据定义的话，FP应该指的是标签为非NA但是预测错的，可能是NA也可能不是NA（即你认为是positive但是实际不是），而FN是标签为NA但是预测为非NA的（即你认为是negative但是实际不是），这个好像完全反过来了。。。
