### ISSUE TITLE
关于ATT的问题

### ISSUE THREAD

**Issue by shuxiaobo** [ShomyLiu/pytorch-relation-extraction#3]
看了您复现论文的笔记，发现Att的效果略差，我down了代码跑了之后发现，评价方法的att的评价方法的那个参数2000是不是有问题？论文中没有提到top2000，翻了thunlp重新实现的版本，也没发现2000这个参数

**Comment by ShomyLiu** [comment]
@shuxiaobo  当时复现是按照paper和当时的C++代码复现的，尤其是evalution部分: 参考https://github.com/thunlp/NRE/blob/master/PCNN%2BATT/test.h#L236   这里是取了Top2000的。在实际的评测画图中，也是需要取Top的，可能是2000或者3000。 在thunlp最新的实现OpenNRE的结果也已经说明了ATT和ONE效果基本一样(https://github.com/thunlp/OpenNRE/blob/master/images/pcnn.png)  。不过他们的新的实现结果普遍都要偏高一些。

但是在小数据27类上，个人跑出的结果的确有点差，有点奇怪。
