### ISSUE TITLE
关于Manual Evaluation

### ISSUE THREAD

**Issue by ShellingFord221** [ShomyLiu/pytorch-relation-extraction#30]
你好！虽然你的代码里没有关于手工检测的部分，但看了PCNN原始论文还是很困惑。

当recall很低的时候，there is a sharp decline of precision，文中说原因是suffer from FN examples。但是当recall变化很小时，应该是FP急剧增大导致的precision急剧变小吧，也就是标签为NA，但预测为非NA的sample增多。但是如果按照文中说法，FN samples才是这个现象的原因，而FN指的是样本标签为非NA，但预测为NA的。可是这一部分跟freebase的不完整性有什么关系？

谢谢！

**Comment by ShomyLiu** [comment]
对 我跟你理解是一样。 这里的FN我觉得应该是针对于远程监督说的，而不是关系抽取模型。 在远程监督产生语料的过程中，FN即：将非NA标记为NA.
