### ISSUE TITLE
数据集格式的问题

### ISSUE THREAD

**Issue by isolet** [ShomyLiu/pytorch-relation-extraction#31]
你好，我看了一下bags_train.txt里的数据，与README里的描述的不太一样，是否有误？

    m.010016    m.0492jkz   NA  542694
    denton,daisy_hill,34,0,0,44
    0,2,4,525,6,112,15099,2138,6,4149,2,0,2,8,5338,2138,6,335,2,20,904,73,908,9,1083,3997,7409,2,4,400,6,0,0,6,29209,2,0,2,8,4,282,13060,7409,3
    84,83,82,81,80,79,78,77,76,75,74,73,72,71,70,69,68,67,66,65,64,63,62,61,60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41
    50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7
    1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3

```
数据格式简单说明:

第一行: 两个实体ID: ent1id ent2id
第二行: bag标签和bag内句子个数，其中由于少数bag有多个label(不会超过4个)，因此句子label用4个整数表示，-1表示为空，如: 2 4 -1 -1 3 表示该bag的标签为2和4，然后包含3个句子
后续几行表示该bag内的句子
```

请问`parse_sen`函数里的对应解析txt文件里的`ldist`, `rdist`这些是什么意思？

**Comment by ShomyLiu** [comment]
不好意思，后续更新代码，未修改readme。
ldist 表示： 每个单词距离第一个实体(左实体)的距离
rdist：每个单词距离第二个实体（右实体）的距离
最后的1,2,3表示的是掩码，用来计算piecewise pooling.

**Comment by Fengzhu-xu** [comment]
请问，拿来用的数据是bags_feature.npy和label.npy还是w2v.npy,p1_2v.npy.p2_2v.npy？
