### ISSUE TITLE
object of type 'zip' has no len()

### ISSUE THREAD

**Issue by MQ99** [ShomyLiu/pytorch-relation-extraction#32]
请问一下，我正常运行train（）方法，object of type 'zip' has no len()，这是怎么回事？对应代码如下：
main_mil.py：
print('train data: {}; test data: {}'.format(len(train_data), len(test_data)))

filternyt.py：
    def __len__(self):
        return len(self.x)
![Uploading image.png…]()

**Comment by ShomyLiu** [comment]
应该是python2->3的问题， 如果用的python3的话，可以把有zip ， map 关键词的语句，前面加一个list，如 return len(list(self.x))
