### ISSUE TITLE
filternyt.py 中的self.limit代表什么意义？

### ISSUE THREAD

**Issue by cswangjiawei** [ShomyLiu/pytorch-relation-extraction#33]
FilterNYTLoad类中的limit代表什么意义？还有在函数get_pos_feature中计算pf1、pf2时，相对距离都加了2 `pf1 += list(map(padding, index - ent_pos[0] + 2 + self.limit))`，在句子两边padding并不影响单词距实体之间的相对距离呀，为什么要加2呢？

**Comment by ShomyLiu** [comment]
limit其实就是计算相对距离，计算postion embedding需要的。 比如limit=50的话，就是把word距离entity最远距离设置100 （-50-50）。 加padding不影响相对距离，padding的作用是补0，方便模型中的piecewise pooling 操作。主要是一些边界操作，比如某个实体在句子的第一个位置，这样，piecewise的分段，第一段就为空了。

**Comment by cswangjiawei** [comment]
既然padding不影响相对距离，为什么计算相对距离的时候加2呢：
`pf1 += list(map(padding, index - ent_pos[0] + 2 + self.limit))
pf2 += list(map(padding, index - ent_pos[1] + 2 + self.limit))`
为什不是
`pf1 += list(map(padding, index - ent_pos[0] + self.limit))
pf2 += list(map(padding, index - ent_pos[1]  + self.limit))`

**Comment by cswangjiawei** [comment]
请问楼主还在吗？那个地方为什么加2呀？还有filternyt.py第130行`epos = list(map(lambda x: int(x) + 1, sent[0:2]))`，将实体的index加1了，但是在get_pad_sen()函数中，`sen.insert(0, self.word2id['BLANK'])`被注释了，即176行`# sen.insert(0, self.word2id['BLANK'])`,所以第130行是不是应该改为`epos = list(map(lambda x: int(x), sent[0:2]))`？

**Comment by ShomyLiu** [comment]
1. pf1, pf2 这个加不加2 其实没有任何影响，只是为了将相对距离（-50-50）改到（0-100） 作为 position embedding.  我没记错的话，当时+2 可能是考虑到了上限 是 2*limit + 2  所以加了2. 不过刚刚又想了想，加不加没有啥区别，毕竟只是作为随机初始化的Embedding的索引。
2. 对，严谨来说，是需要去掉注释的。 不过也不影响最后的结果，因为模型中，并不需要知道entity是在什么位置，这个是由position Embedding 控制。
3. 因为近些年的RE paper大部分使用Large NYT 数据集，我们后续调整更新代码均是基于Large NYT (nyt.py) ，可能在filternyt.py上有一些问题，没及时解决，表示抱歉。 不过建议使用LargeNYT数据。

**Comment by cswangjiawei** [comment]
懂了，感谢作者耐心的解答！
