### ISSUE TITLE
关于关系中实体的顺序

### ISSUE THREAD

**Issue by cswangjiawei** [ShomyLiu/pytorch-relation-extraction#34]
请教作者一个问题，在训练语料和测试语料中都给出了关系中实体的顺序，比如对于关系(Queens,contains,Belle_Harbor),皇后区与贝尔港的关系是包含关系，所有的训练样例均指明了Queens是实体1， Belle_Harbor是实体2. 并有样例“Sen. charles e. schumer called on federal safety officials yesterday to reopen their investigation into the fatal crash of a passenger jet in Belle_harbor , Queens , because equipment failure , not pilot error , might have been the cause .”  但在实际应用中如何知道句子中的两个实体，在某一种关系中，哪个是实体1，哪个是实体2。就像上面那句，在抽取关系时，如何知道是抽取Belle_harbor , Queens的关系还是Queens, Belle_harbor 的关系？

**Comment by ShomyLiu** [comment]
关于实体顺序的问题，在distant supervised relation extraction中，是没有考虑的，只能通过训练集来学习。 不过在fully supervised RE中，因为关系标签中，存在 direction，即 a->b 和 b<-a 是两种标签，可以解决这个问题。

**Comment by cswangjiawei** [comment]
懂了，感谢作者的解答
