### ISSUE TITLE
卷积方式

### ISSUE THREAD

**Issue by cswangjiawei** [ShomyLiu/pytorch-relation-extraction#36]
我在看论文《Distant Supervision for Relation Extraction via Piecewise Convolutional Neural Networks》和《Neural Relation Extraction with Selective Attention over Instances》时，论文中所写的卷积都不是等长卷积，论文中讲一个长为s的序列，经过卷积后，将得到长度为s+w-1(w为核宽）。然而，就两篇论文对数据的处理来看，采用的似乎都是等长卷积，比如论文《Neural Relation Extraction with Selective Attention over Instances》，经过extract.cpp处理后得到的文件中，mask的长度都是等于句子长度s的，而不是s+w-1。请教一下作者，两篇论文的源码在实现时，使用的到底是等长卷积还是论文的所写的非等长卷积呀

**Comment by ShomyLiu** [comment]
你好，我们实现的时候，也用的等长卷积，即加了padding， 这个其实无所谓，效果差异不大。
