### ISSUE TITLE
想问下PR曲线图是怎么画出来的呢？

### ISSUE THREAD

**Issue by buppt** [ShomyLiu/pytorch-relation-extraction#4]
看到你博客中的PR图，召回率越大，准确率就越小，recall最大才到0.5，而这时的准确率都比0.5要小了。

但是论文里最终的结果不是准确率和召回率都大于80%了么？

想知道PR图是怎么画的呢？

**Comment by ShomyLiu** [comment]
@buppt  “论文里最终的结果不是准确率和召回率都大于80%” 这个应该是全监督的关系抽取的performance， 一般F1 在80%多，数据集一般用SemEval2010,  比如 Attention-Based Bidirectional Long Short-Term Memory Networks for Relation Classification 的。 不过博客记录的是远程监督的关系抽取，一般是画PR图曲线，因为远程监督有噪音，所以不能简单用F1指标。 比如Distant Supervision for Relation Extraction via Piecewise Convolutional Neural Networks.

**Comment by buppt** [comment]
原来是这样，是我弄混了，多谢！
