### ISSUE TITLE
关于数据集格式的问题

### ISSUE THREAD

**Issue by rylynn-abo** [ShomyLiu/pytorch-relation-extraction#47]
roger_mcnamee,elevation_partners,10,16,0,30
3733,0,2434,20,82184,24,2451,2,0,21,106333,2,7,2475,225,22,0,2,4,2541,827,636,121,0,3065,15,7,4303,3,0
60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31
66,65,64,63,62,61,60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37
1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3

你好，以上是数据集中的一个关系实例。
* NYT+Freebase数据集每个关系实例的第一行的后四个数字是什么意思？没能理解代码的意思，也没在网上找到相应的介绍的文档，如这个实例中的10,16,0,30是什么意思？
* 每个实例的第三、四行是position的相对位置为什么从一个这么大的值开始递减，如这个例子中为什么要分别从60和66开始递减。
* 如果能附加上具体的数据集说明就更好了！

**Comment by rylynn-abo** [comment]
看懂了，各个数据的意义如下：

entity_1, entity_2    relation_type(NA or other)  instance_1_id, instance_2_id,...,instance_n_id
(relation1)
source_entity_name, destination_entity_name, source_entity_position, destination_entity_position, relation_id, sentence_length
word_1_id, word_2_id,...,word_{sentence_length}_id
word_1_distance2source_entity, word_2_distance2source_entity,...,word_{sentence_length}_distance2source_entity (50 represents that the relative distance is 0)
word_1_distance2destination_entity, word_2_distance2destination_entity,...,word_{sentence_length}_distance2destination_entity (50 represents that the relative distance is 0)
word_1_piece, word_2_piece,...,word_{sentence_length}_piece

**Comment by ShomyLiu** [comment]
差不多，参考 #31

**Comment by rylynn-abo** [comment]
还有一个问题，就是作者在文章中说是通过SGD进行训练，但是又用的是mini-batches，这两者是不是矛盾了？那每次梯度下降到底是用一个实例还是用batch_size个实例进行训练呢？


<img width="408" alt="Screenshot 2020-01-07 at 7 10 38 PM" src="https://user-images.githubusercontent.com/20431361/71891342-6566ce80-3181-11ea-8b65-1435d9f166e6.png">

**Comment by ShomyLiu** [comment]
绝大部分 bag-level的relation extraction的 基本单元就是 以 entiti pair 为单位训练的，也就是一个instance，训练的时候，是计算batch个实例的loss

**Comment by rylynn-abo** [comment]
那如果每次通过整个batch的loss进行梯度下降的话，那使用的就不是SGD了吧，SGD指的应该是每次下降只使用一个instance的loss？

**Comment by ShomyLiu** [comment]
文中这里的SGD 可能更指的是优化方法

**Comment by Gavin4th** [comment]
感谢大佬的解惑

**Comment by niuweicai** [comment]
> 看懂了，各个数据的意义如下：
> 
> entity_1, entity_2 relation_type(NA or other) instance_1_id, instance_2_id,...,instance_n_id
> (relation1)
> source_entity_name, destination_entity_name, source_entity_position, destination_entity_position, relation_id, sentence_length
> word_1_id, word_2_id,...,word_{sentence_length}_id word_1_distance2source_entity, word_2_distance2source_entity,...,word_{sentence_length}_distance2source_entity (50 represents that the relative distance is 0) word_1_distance2destination_entity, word_2_distance2destination_entity,...,word_{sentence_length}_distance2destination_entity (50 represents that the relative distance is 0) word_1_piece, word_2_piece,...,word_{sentence_length}_piece

您好，看了您的数据集格式的解释，有几个地方不太明白：
1.m.010016	m.0492jkz	NA	542694  您说542694代表实例的id，可是为什么生成的bags_train.txt每个实例前面都有这一行，为什么不是隔6（542694）个实例出现一次呢。
2.您说的单词to实体的位置数字代表的含义我没明白，例如你自己举得例子‘每个实例的第三、四行是position的相对位置为什么从一个这么大的值开始递减，如这个例子中为什么要分别从60和66开始递减。’

希望能得到您的解答

**Comment by ShomyLiu** [comment]
你好！ bags_train.txt 已发邮箱，请查收。
目前看感觉应该是您那边的CPP代码有问题，建议重新pull下，再跑一下。
