### ISSUE TITLE
filternyt.py中实体位置的处理

### ISSUE THREAD

**Issue by LiuZhenXian** [ShomyLiu/pytorch-relation-extraction#52]
epos = list(map(lambda x: int(x) + 1, sent[0:2]))
您好，为什么这里要 int(x)+1？

**Comment by ShomyLiu** [comment]
这个暂时没有用处了，我记得最终使用的是：
https://github.com/ShomyLiu/pytorch-relation-extraction/blob/master/dataset/filternyt.py#L129 
的`postions`

**Comment by LiuZhenXian** [comment]
> 这个暂时没有用处了，我记得最终使用的是：
> https://github.com/ShomyLiu/pytorch-relation-extraction/blob/master/dataset/filternyt.py#L129
> 的`postions`

看到了后来用的mask。没往后面看。谢谢啊
