### ISSUE TITLE
关于标签attention

### ISSUE THREAD

**Issue by LiuZhenXian** [ShomyLiu/pytorch-relation-extraction#57]
您好，之前看到您的博客里面提到Zhu, (2017). Relation Classification via Target-Concentrated Attention CNNs. ICONIP这篇文章，句子中每个单词与标签做attention，训练阶段是有真实标签的，那测试阶段的relation标签怎么获得呢？

**Comment by ShomyLiu** [comment]
这个跟PCNN+ATT类似。在测试阶段都是遍历所有的relation来计算所有relation 下的attention weight，最后选择最好的吧。

**Comment by LiuZhenXian** [comment]
理解了，真的谢谢你，这个问题一直想不通，后来在实验室做项目的时候用到远程监督，看到有和relation做attention的，就想来这问问您，谢谢哈。

**Comment by ShomyLiu** [comment]
不用谢~
