### ISSUE TITLE
ACCURACY

### ISSUE THREAD

**Issue by charlesfufu** [ShomyLiu/pytorch-relation-extraction#6]
![image](https://user-images.githubusercontent.com/33311822/47192270-c2107a80-d37e-11e8-86c1-2fcb9c00fe5f.png)
你好，请问这个准确率感觉有点低，不知道你训练的最后准确率是多少？

**Comment by ShomyLiu** [comment]
远程监督的关系抽取，一般最后的准确率不是关键的参数，需要等看每次的PR曲线。 最后大概precison+recall 可以到0.8-0.9的样子。

**Comment by charlesfufu** [comment]
> 远程监督的关系抽取，一般最后的准确率不是关键的参数，需要等看每次的PR曲线。 最后大概precison+recall 可以到0.8-0.9的样子。

刚刚学习关系抽取，可以加楼主个联系方式。有机会想多多请假楼主。微信联系方式邮箱发楼主你。

**Comment by ShomyLiu** [comment]
OK, shomyliu#gmail.com

**Comment by qwerfdsaplking** [comment]
> > 远程监督的关系抽取，一般最后的准确率不是关键的参数，需要等看每次的PR曲线。 最后大概precison+recall 可以到0.8-0.9的样子。
> 
> 刚刚学习关系抽取，可以加楼主个联系方式。有机会想多多请假楼主。微信联系方式邮箱发楼主你。

你好，我建了个关系抽取的QQ群711741227，有兴趣可以加进来一起研究

**Comment by Veyronl** [comment]
![image](https://user-images.githubusercontent.com/46363468/58689416-9005d300-83b9-11e9-9153-9b189aef85b9.png)
@ShomyLiu 1.如果看precision+recal的话在0.84左右,但是单独看两者都是在震荡,Loss也是一直在下降.
2.为什么远程监督的关系抽取,不是很看重的最后的准确率呢,?是因为每次只抽取bag里面的1个instance,如果是NA则不计入precision/recall总数吗

**Comment by ShomyLiu** [comment]
这俩问题个人感觉本质一样。 远程监督中， 后面的recall或者precision已经很低了，因此没有什么意义了。因为计算PR的时候，先对预测的概率排名，然后从大到小计算，因此前面那些才会有价值。 此外NA在evaluation的时候不计算。

**Comment by Veyronl** [comment]
感谢你的回答,
那从我的截图上看,目前的训练是否是正确的呢?(采用的Large data和use_pcnn)

**Comment by ShomyLiu** [comment]
@Veyronl  应该是争取的

**Comment by ShellingFord221** [comment]
你好，如果我不是基于bag这种思想的话，只是把每个句子及其标签当成普通分类问题去做，那我的PR曲线该如何去画呢？对于每一个类别，可以按照概率升序排列作为阈值，计算PR点然后画图，但是这样的话总体（53个类）的PR曲线该怎么画呢？因为我看到别人论文里都是整个数据集的PR曲线。谢谢！

**Comment by ShellingFord221** [comment]
我看了你的代码，感觉还是把这53个类当成了二分类（即NA和非NA）问题去计算TP, FN, FP的。也就是说，FP指的是label为NA，预测不是NA的；FN指的是实际非NA，预测为NA的；TP指的是实际不是NA，预测也不是NA，但预测标签与实际标签一致的。但是fp_res变量是用来记录什么的呢？

**Comment by ShomyLiu** [comment]
本质是这个意思，但是不算是二分类，而是NA需要过滤掉，不能算入最终的evaluation, 因为NA的数量太多了，如果考虑了NA的话，那么准确率会非常高，但是没有意义， 系抽取是为了识别非NA的。

1. fp_res 是当时为了做case study 存的变量，在绘制PR曲线中，我记得是用不到。
2. last_pre > 0.24 and last_rec > 0.24 这个没有什么特殊意思。因为开始一些pre和rec比较小，存储也没有用。 
-----
上一个issue， 如果是sentence-level的话， 就没有必要画PR曲线了啊，直接计算最终的precision, recall, F1就好了呀。

**Comment by ShellingFord221** [comment]
谢谢回答！但是还有几处想请教：

1. 为什么如果是sentence-level的话，就不必画PR曲线了呢？是不是因为sentence-level是把NA当成普通的一个类别对待，所以只要计算F1值就可以了呢？

2. 接着上面的问题，如果我只是把NA当成53个类中的一种，不把它看成负例的话，那么这样多分类的PR曲线中的值对该怎么计算呢？因为每个类别的阈值可能不同啊，每个类分别计算了PR值对怎么融合到一张图里呢？

3. 在utils.py文件中，line 45~line 71:
for idx in range(len(true_y)):
        i = true_y[index[idx]]
        j = pred_y[index[idx]]
        # 统计fp, fn, tp
        ...
        if fp + tp == 0:
            precision = 1.0
        else:
            precision = tp * 1.0 / (tp + fp)
        recall = tp * 1.0 / positive_num
        if precision != all_pre[-1] or recall != all_rec[-1]:
            all_pre.append(precision)
            all_rec.append(recall)
这一段代码是计算PR值的，为什么统计了一个点的fp, fn, tp值以后就计算precision和recall，而不是扫了所有数据之后统计fp, fn, tp值再计算precision和recall呢？（即line 64~line 71 shift+tab，放在for idx in range(len(true_y))循环的外面）

谢谢！
