### ISSUE TITLE
关于数据预处理的参数问题

### ISSUE THREAD

**Issue by hhhOscar** [ShomyLiu/pytorch-relation-extraction#66]
![image](https://user-images.githubusercontent.com/29939882/100841941-01dd4200-34b3-11eb-8e9f-1941b69317cd.png)
请问这里的limit是实体左右需要计算距离的长度吗？
![image](https://user-images.githubusercontent.com/29939882/100842051-3650fe00-34b3-11eb-8e86-6a5e7bc6d75f.png)
如果按照limit*2+1来算 一个实体需要101个距离向量 这不是超出句子的max_len=80了吗？是不是设置成40比较合理呢

**Comment by 599177227** [comment]
+1 ,这个问题有谁能回答一下吗？

**Comment by 599177227** [comment]
如果按照limit*2+1来算 一个实体需要101个距离向量 这不是超出句子的max_len=80了吗？是不是设置成40比较合理呢 @shuxiaobo
