### ISSUE TITLE
关于Evaluation

### ISSUE THREAD

**Issue by 13Lingzi** [ShomyLiu/pytorch-relation-extraction#7]
您好，请问一下，远程监督关系抽取在做evaluation的时候，是怎样求得p和r的值呢？其中标签为NA的怎么处理它，一直没有搞明白远程监督关系抽取这块evaluation的方式。

**Comment by CrisJk** [comment]
同问
1. 因为一对实体可能有多种关系。我在做远程监督的时候，对于一个句子中的一对实体，会把每一种关系分别作为一个样本。打个比方：“比尔盖茨”和“微软”有两种关系，一种是“创立者”，另一种是“员工”，那么对于“比尔盖茨创立了微软”这句话，我会把它当作两个样本，一个包含关系“创立者”，另一个包含关系“员工”。这种情况在评估的时候应该怎么算precision?看您的代码似乎是只要目标实体对包含预测得到的label，则算预测正确。很多论文里似乎没有怎么提到metric的公式，所以想问一下大家是不是普遍用的这种方法。

2. NA的样本如何获得？我目前想到的方法有两种，一种是遍历知识库中现有的实体对，把知识库中不存在关系的实体对当作NA，但由于知识库中知识不全，并且关系提取最终目的就是找到知识库中没有的关系，所以这种方法不太合适；另一种是人工标注NA数据。请问有没有更合适的方法获取NA样本?

**Comment by ShomyLiu** [comment]
@13Lingzi @CrisJk  
1. 首先计算precision和recall的时候， 忽略NA。但是计算false positive时候，比如将NA预测为某一个postive relation, 这个时候， fp 是需要+1的。 然后计算精度就是: tp/(tp + fp).  而计算recall就比较简单了，就是查全率，直接tp/all_postive_num.  
这个过程是首先按照预测概率排序的，然后一个一个的去计算，所以开始阶段，recall肯定很低的，毕竟tp小。 但是precision相对较高。
2. 对于多标签的时候，如果是softmax做分类了，那就按照代码中的只要可以预测正确就算对。 也有专门的文章，设计了多标签的loss函数。 

上面的计算metric的方法 我是按照Zeng 2015那篇文章代码中计算方法来的。

3. NA的样本，distant supervision in RE 在Mintz 2009(Distant supervision for relation extraction without labeled data)那篇文章提出的,  我记得 NA 是作为负样本随机采的，具体可以看下那篇文章。

**Comment by CrisJk** [comment]
> @13Lingzi @CrisJk
> 
> 1. 首先计算precision和recall的时候， 忽略NA。但是计算false positive时候，比如将NA预测为某一个postive relation, 这个时候， fp 是需要+1的。 然后计算精度就是: tp/(tp + fp).  而计算recall就比较简单了，就是查全率，直接tp/all_postive_num.
>    这个过程是首先按照预测概率排序的，然后一个一个的去计算，所以开始阶段，recall肯定很低的，毕竟tp小。 但是precision相对较高。
> 2. 对于多标签的时候，如果是softmax做分类了，那就按照代码中的只要可以预测正确就算对。 也有专门的文章，设计了多标签的loss函数。
> 
> 上面的计算metric的方法 我是按照Zeng 2015那篇文章代码中计算方法来的。
> 
> 1. NA的样本，distant supervision in RE 在Mintz 2009(Distant supervision for relation extraction without labeled data)那篇文章提出的,  我记得 NA 是作为负样本随机采的，具体可以看下那篇文章。

感谢！

**Comment by 13Lingzi** [comment]
> @ 13Lingzi @CrisJk
> 
> 1. 首先计算精确和召回的时候，忽略NA。但是计算假阳性时候，比如将NA预测为某一个积极关系，这个时候，fp是需要+1的。然后计算精度就是：tp /（tp + fp）。而计算召回比较简单了，就是查全率，直接tp / all_postive_num。
>    这个过程是首先按照预测概率排序的，然后一个一个一个的去计算，所以开始阶段，召回肯定很低的，毕竟tp小。但是精度相对较高。
> 2. 对于多标签的时候，如果是softmax做分类了，那就按照代码中的只要可以预测正确就算对。也有专门的文章，设计了多标签的loss函数。
> 
> 上面的计算公制的方法我是按照Zeng 2015那篇文章代码中计算方法来的。
> 
> 1. NA的样本，RE在Mintz 2009中的远程监督（没有标记数据的关系提取的远程监督）那篇文章提出的，我记得NA是作为负样本随机采的，具体可以看下那篇文章。

thx！
