### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by 13Lingzi** [ShomyLiu/pytorch-relation-extraction#8]
您好，请问一下在远程监督关系抽取中，Evaluaton的部分是怎么计算P和R 的值，标签为NA的数据是怎么处理的？

**Comment by ShomyLiu** [comment]
对于所有的bags，按照预测了标签的概率从大到小排序。  之后循环一个一个的计算PR,可以参考对应的函数代码：https://github.com/ShomyLiu/pytorch-relation-extraction/blob/master/utils.py#L29
